6777 talks page migration
jugua/conference pull request #123
Opened 2017-10-13 08:44 UTC by kris45

2017-10-13 08:58 UTC, SupraVlad requested changes

2017-10-13 08:58 UTC, SupraVlad commented on conference/react-js/src/containers/Talks/DisplayTalks/index.jsx
> +  setTalks = data => Object.values(data)
is `data` an object or array? why do you use `Object.values` here?

2017-10-13 08:58 UTC, SupraVlad commented on conference/react-js/src/containers/Talks/FilterForm/index.jsx
> +    Object.values(listOfTopics).map(({ name, id }) => (
the same question about `Object.values`

2017-10-13 08:58 UTC, SupraVlad commented on conference/react-js/src/containers/Talks/index.jsx
> +          <div className="data-table">
why do you use `div` instead of `table` for creating a table?

2017-10-13 08:58 UTC, SupraVlad commented on conference/react-js/src/reducers/talks.js
> +    return [...res];
how about simply returning `listOfTalks.filter(filtered)`? does it make sense?

2017-10-13 08:58 UTC, SupraVlad commented on conference/react-js/src/components/Talks/Form-components/InputBox.jsx
> -import React from 'react';
why have you removed it? for `InputBox`, `TextareaBox` and `Speaker-info-popup`

2017-10-17 08:38 UTC, SupraVlad approved these changes

2017-10-17 08:55 UTC, blyzniuk commented on conference/react-js/src/components/Talks/TalksList/index.jsx
> +  talks: {},
Do you use it?

2017-10-17 08:55 UTC, blyzniuk commented on conference/react-js/src/containers/Talks/index.jsx
> +    this.state.status = e.target.value;
setState ?

2017-10-17 08:55 UTC, blyzniuk commented on conference/react-js/src/actions/load.js
> +const load = (actionType, data) => ({
I saw the same action function in one of previous PR. Could you check it?

2017-10-17 09:24 UTC, blyzniuk approved these changes

2017-10-17 09:25 UTC, merged