Copied Talks component to My talk and added sort functionality
jugua/conference pull request #134
Opened 2017-10-17 15:59 UTC by ScreamCat1

2017-10-20 07:06 UTC, SupraVlad requested changes

2017-10-20 07:06 UTC, SupraVlad commented on conference/react-js/src/reducers/talks.js
> +    return [...action.payload];
seems like you can return `action.payload` by itself. I see no sense of using `spread` operator along with square brackets

2017-10-20 07:06 UTC, SupraVlad commented on conference/react-js/src/reducers/userTalks.js
> +    return [...talks.sort(sortDirection)];
same point about usage of `spread` + square brackets

2017-10-20 07:31 UTC, SupraVlad approved these changes

2017-10-23 10:04 UTC, asanametove commented on conference/react-js/src/components/Autorized-user-menu/index.jsx
> +      (<li className="tabs-list__item">
I think you can write "length && <li ..." there

2017-10-23 10:04 UTC, asanametove commented on conference/react-js/src/containers/Talks/index.jsx
> +    if (tagName === 'TH' && name !== undefined) {
Maybe "tagName === 'TH' && name" will be enough?

2017-10-23 10:04 UTC, asanametove commented on conference/react-js/src/reducers/talks.js
>  const talks = (state = talksInitial, action) => {
"const talks = (state = talksInitial, { type, payload })" looks better I think

2017-10-23 11:13 UTC, ScreamCat1 commented on conference/react-js/src/components/Autorized-user-menu/index.jsx
> +      (<li className="tabs-list__item">
написал length > 0 && (<li...

2017-10-23 11:51 UTC, asanametove approved these changes

2017-10-23 11:52 UTC, merged