7135 add filters
jugua/conference pull request #177
Opened 2017-11-14 15:34 UTC by kris45

2017-11-14 16:59 UTC, ScreamCat1 commented on conference/react-js/src/reducers/talks.js
> +      filter: { conferenceName, title, status },
We need some else functionality for filters. This reducer should take different numbers of filter fields

2017-11-14 17:02 UTC, ScreamCat1 commented on conference/react-js/src/containers/Talks/index.jsx
> +      filter: { conferenceName: '', title: '', status: '' },
We want use this function to another data (in My talks and Talks components). So number of fields will be different

2017-11-14 17:03 UTC, ScreamCat1 commented on conference/react-js/src/containers/Talks/index.jsx
> +      filter: { conferenceName: '', title: '', status: '' },
Same problem

2017-11-15 10:28 UTC, SupraVlad requested changes

2017-11-15 10:28 UTC, SupraVlad commented on conference/react-js/src/containers/Talks/FilterForm/index.jsx
> +  setStatus = status => (status.map(element =>
as I've noticed, this method returns a list of elements(options) so the name `getOptions` will mach better

2017-11-15 10:28 UTC, SupraVlad commented on conference/react-js/src/containers/Talks/FilterForm/index.jsx
>              <label
I remember we have custom component for label+input. reuse it, please

2017-11-15 10:59 UTC, SupraVlad approved these changes

2017-11-15 11:00 UTC, asanametove approved these changes

2017-11-15 11:01 UTC, merged