7279 change drop down menu
jugua/conference pull request #183
Opened 2017-11-16 15:52 UTC by asanametove

2017-11-17 08:35 UTC, ScreamCat1 commented on conference/react-js/src/components/Tabs/Tabs.jsx
> +          getLinks(talksCount, conferenceCount, role)
I think, you can write map function with add NavLink inside getLinks

2017-11-17 08:35 UTC, ScreamCat1 commented on conference/react-js/src/components/UserMenu/UserMenu.jsx
> +import MenuItem from './MenuItem';
Are you sure about we need this component? We used it only once, and you can can write this easier (use li and Link with className to sign-in and out)

2017-11-17 08:35 UTC, ScreamCat1 commented on conference/react-js/src/containers/ManageUsers/ManageUsers.jsx
> +          Add New User
Linter did not fix it. But, i think, You should use more indents when write text

2017-11-20 12:37 UTC, ScreamCat1 approved these changes

2017-11-20 14:10 UTC, SupraVlad requested changes

2017-11-20 14:10 UTC, SupraVlad commented on conference/react-js/src/components/Tabs/Tabs.jsx
> +        <Route
let's extract this list to separate variable. it is getting bigger and bigger seems to me

2017-11-20 15:54 UTC, SupraVlad approved these changes

2017-11-21 09:40 UTC, merged