7309 fix sorting arrows
jugua/conference pull request #186
Opened 2017-11-20 13:33 UTC by TanyaGordiychuk

2017-11-20 13:45 UTC, ScreamCat1 commented on conference/react-js/src/components/Talks/TalksTable/TalksTable.jsx
> +        className="table-header__item "
Excess space. Delete it please.

2017-11-20 13:45 UTC, ScreamCat1 commented on conference/react-js/src/components/Talks/TalksTable/TalksTable.jsx
> +
Delete empty line please

2017-11-20 13:45 UTC, ScreamCat1 commented on conference/react-js/src/containers/Talks/talks.scss
> +		&__active {
Large indents.Fix it please

2017-11-20 13:49 UTC, TanyaGordiychuk commented on conference/react-js/src/containers/Talks/talks.scss
> +		&__active {
There are no such fields any more

2017-11-21 09:53 UTC, ScreamCat1 approved these changes

2017-11-21 11:50 UTC, YaroslavPerepelychnyi requested changes

2017-11-21 11:50 UTC, YaroslavPerepelychnyi commented on conference/react-js/src/containers/Talks/talks.scss
> +    &__active {
according to bem for modifier should use "--" or "_"

2017-11-21 11:57 UTC, SupraVlad commented on conference/react-js/src/containers/Talks/index.jsx
> +      if (currentEl.indexOf('table-header__item_active') !== -1) {
there is a method `includes`. it is used to define whether string/array contains defined symbol/element.
you may use it

2017-11-21 11:58 UTC, SupraVlad approved these changes

2017-11-21 12:01 UTC, YaroslavPerepelychnyi approved these changes

2017-11-21 12:04 UTC, merged