7461 change and add filters on organiser event
jugua/conference pull request #209
Opened 2017-12-06 12:37 UTC by kris45

2017-12-06 12:51 UTC, AlexKutkanych approved these changes

2017-12-06 13:48 UTC, SupraVlad requested changes

2017-12-06 13:48 UTC, SupraVlad commented on conference/react-js/src/reducers/talks.js
> +      countTopic > -1;
to improve readability you may use
[includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) method.
this piece of code looks quite complex

2017-12-11 10:45 UTC, SupraVlad approved these changes

2017-12-11 12:35 UTC, merged